# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.set_news_image_name, verbose_name='Изображение')),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Keywords')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'News',
            },
        ),
    ]
