# Generated by Django 2.0.2 on 2018-05-08 21:05

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.set_news_image_name, verbose_name='Small image'),
        ),
    ]
