# Generated by Django 2.0.2 on 2018-12-13 15:41

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_promo_small_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ('-created',), 'verbose_name': 'Акции', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterField(
            model_name='promo',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.set_news_image_name, verbose_name='Маленькое изображение'),
        ),
    ]
