# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
