# Generated by Django 2.0.1 on 2018-01-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20171213_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
