# Generated by Django 2.0.1 on 2018-01-22 19:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180115_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' ', verbose_name='Информация о поставщике'),
            preserve_default=False,
        ),
    ]
