# Generated by Django 2.0.1 on 2018-02-02 19:54

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20171206_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=profile.models.set_profile_image_name, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения'),
        ),
    ]
