# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Keywords'),
        ),
    ]
