# Generated by Django 2.0.1 on 2018-02-05 18:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180205_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='use',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Use'),
        ),
    ]
