# Generated by Django 2.0.1 on 2018-02-05 18:58

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180205_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=catalog.models.set_file_name, verbose_name='Файл'),
        ),
    ]
