# Generated by Django 2.0.1 on 2018-02-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180223_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='alt',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO alt'),
        ),
    ]
