# Generated by Django 2.0.1 on 2018-02-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20180202_2154'),
        ('catalog', '0018_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('digit', models.CharField(max_length=150, verbose_name='Digit')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtitle')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Digit',
                'verbose_name_plural': 'Digits',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='countries',
            field=models.ManyToManyField(blank=True, to='geo.Region'),
        ),
        migrations.AddField(
            model_name='digits',
            name='product',
            field=models.ForeignKey(on_delete=None, to='catalog.Product', verbose_name='Продукт'),
        ),
    ]
