# Generated by Django 2.0.1 on 2018-02-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20180227_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_use',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Use block title'),
        ),
    ]
