# Generated by Django 2.0.1 on 2018-02-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_color',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Color block title'),
        ),
    ]
