# Generated by Django 2.0.3 on 2018-03-23 17:56

import catalog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import phonenumber_field.modelfields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_product_title_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Выгода', 'verbose_name_plural': 'Выгоды'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цветовой вариант', 'verbose_name_plural': 'Цветовые варианты'},
        ),
        migrations.AlterModelOptions(
            name='digits',
            options={'verbose_name': 'Цифра', 'verbose_name_plural': 'Цифры'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Фотогалерея', 'verbose_name_plural': 'Фотогалереи'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='digits',
            name='digit',
            field=models.CharField(max_length=150, verbose_name='Цифра'),
        ),
        migrations.AlterField(
            model_name='digits',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=catalog.models.set_image_logo_name, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_benefit',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Выгоды'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_color',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока ЦВЕТОВЫЕ ВАРИАНТЫ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Карта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_digits',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Цифры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_documents',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Документы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_features',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_gallery',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Фотогалерея'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_use',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Использование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Видео'),
        ),
        migrations.AlterField(
            model_name='product',
            name='use',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Использование'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(verbose_name='Ссылка на видео в youtube'),
        ),
    ]
