# Generated by Django 2.0.3 on 2018-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20180323_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Сортировка'),
        ),
    ]
