# Generated by Django 2.0.2 on 2019-10-08 18:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_product_is_checked'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description_aux_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description aux'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_aux_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description aux'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_benefit_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Выгоды'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_benefit_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Выгоды'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_color_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока ЦВЕТОВЫЕ ВАРИАНТЫ'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_color_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока ЦВЕТОВЫЕ ВАРИАНТЫ'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_country_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Карта'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_country_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Карта'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_digits_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Цифры'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_digits_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Цифры'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_documents_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Документы'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_documents_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Документы'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_features_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_features_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_gallery_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Фотогалерея'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_gallery_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Фотогалерея'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_use_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Использование'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_use_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Использование'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_video_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Видео'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_video_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блока Видео'),
        ),
    ]
