# Generated by Django 2.0.2 on 2019-10-11 06:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20191008_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Использование'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Использование'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_aux',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание aux'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_aux_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание aux'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_aux_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание aux'),
        ),
    ]
