# Generated by Django 2.0.2 on 2019-10-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20191011_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='color',
            name='alt_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO alt'),
        ),
        migrations.AddField(
            model_name='color',
            name='alt_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO alt'),
        ),
        migrations.AddField(
            model_name='digits',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='digits',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='digits',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='digits',
            name='text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='digits',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='digits',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='feature',
            name='value_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='feature',
            name='value_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO alt'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_uk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SEO alt'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
    ]
