# Generated by Django 2.0.2 on 2019-10-11 06:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20191011_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='meta_keywords_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
    ]
