# Generated by Django 2.0.2 on 2019-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20191011_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='digits',
            name='digit_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Цифра'),
        ),
        migrations.AddField(
            model_name='digits',
            name='digit_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Цифра'),
        ),
    ]
