# Generated by Django 2.0.1 on 2018-03-03 17:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0011_auto_20180226_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=250, verbose_name='Company name')),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('coordinates', models.CharField(max_length=50, verbose_name='Coordinates')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company')),
                ('region', models.ForeignKey(on_delete=None, to='geo.Region', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='OfficeGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Alt')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Office', verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Office gallery',
                'verbose_name_plural': 'Office galleries',
            },
        ),
    ]
