# Generated by Django 2.0.3 on 2018-03-23 17:56

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Alt')),
            ],
            options={
                'verbose_name': 'Office gallery',
                'verbose_name_plural': 'Office galleries',
            },
        ),
        migrations.RemoveField(
            model_name='officegallery',
            name='office',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Офис', 'verbose_name_plural': 'Офисы'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='office',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='office',
            name='coordinates',
            field=models.CharField(max_length=50, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='office',
            name='region',
            field=models.ForeignKey(on_delete=None, to='geo.Region', verbose_name='Страна'),
        ),
        migrations.DeleteModel(
            name='OfficeGallery',
        ),
        migrations.AddField(
            model_name='gallery',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Office', verbose_name='Офис'),
        ),
    ]
