# Generated by Django 2.0.2 on 2019-07-29 19:16

from django.db import migrations, models
import django.db.models.deletion
import solutions.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0029_category_description_aux'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=solutions.models.set_image_name, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
        migrations.CreateModel(
            name='SolProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solproducts', to='catalog.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SolVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=solutions.models.set_image_name, verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена')),
                ('products', models.ManyToManyField(to='catalog.Product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
        migrations.AddField(
            model_name='soloffer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soloffers', to='solutions.SolProduct'),
        ),
    ]
