# Generated by Django 2.0.2 on 2019-07-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvariant',
            options={'verbose_name': 'Ваниант', 'verbose_name_plural': 'Ванианты'},
        ),
        migrations.AddField(
            model_name='solvariant',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.SolOffer'),
        ),
    ]
