# Generated by Django 2.0.2 on 2019-08-03 12:46

from django.db import migrations, models
import django.db.models.deletion
import solutions.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20190729_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='solproduct',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=solutions.models.set_image_name, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='soloffer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='solutions.SolProduct'),
        ),
        migrations.AlterField(
            model_name='solvariant',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='solutions.SolOffer'),
        ),
    ]
