# Generated by Django 2.0.2 on 2019-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20190803_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='solproduct',
            name='slug',
            field=models.SlugField(max_length=170, null=True, unique=True),
        ),
    ]
