# Generated by Django 2.0.2 on 2019-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_solproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='solproduct',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Описание'),
        ),
        migrations.AddField(
            model_name='solproduct',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META Ключевые слова'),
        ),
    ]
