# Generated by Django 2.0.2 on 2019-08-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_auto_20190803_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='solproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
