# Generated by Django 2.0.2 on 2019-08-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_remove_solvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='solproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2019-08-05 19:58', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
