# Generated by Django 2.0.2 on 2019-08-24 18:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0009_auto_20190824_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soloffer',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='solproduct',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
