# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geo.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=geo.models.set_object_image_name, verbose_name='Изображение')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ObjectPPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Keywords')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('products', models.ManyToManyField(to='catalog.Product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=geo.models.set_region_image_name, verbose_name='Изображение')),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='META Keywords')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geo.Region', verbose_name='Parent region')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.AddField(
            model_name='objectppf',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='objectimage',
            name='object_ppf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.ObjectPPF', verbose_name='Object'),
        ),
    ]
