# Generated by Django 2.0 on 2017-12-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectppf',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
