# Generated by Django 2.0 on 2017-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_objectppf_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectppf',
            name='code',
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
