# Generated by Django 2.0 on 2017-12-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20171209_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectppf',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite objects'),
        ),
    ]
