# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_objectppf_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='objectimage',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='objectppf',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
