# Generated by Django 2.0.2 on 2018-05-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20180226_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_auxpage',
            field=models.BooleanField(default=False),
        ),
    ]
