# Generated by Django 2.0.2 on 2018-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_region_is_auxpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='title_eng',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title eng'),
        ),
    ]
