# Generated by Django 2.0.2 on 2018-05-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_region_title_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectppf',
            name='description',
        ),
    ]
