# Generated by Django 2.0.2 on 2018-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0015_remove_objectppf_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='title_eng',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок на английском'),
        ),
    ]
