# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 20:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='return_product',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Возврат'),
        ),
    ]
