# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_delivery_return_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Provider', verbose_name='Поставщик'),
        ),
    ]
