# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_auto_20180115_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='branch',
            new_name='provider',
        ),
    ]
