# Generated by Django 2.0.1 on 2018-01-22 19:51

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_auto_20180115_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=None, related_name='children', to='assistant.Category'),
        ),
    ]
