# Generated by Django 2.0.1 on 2018-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_product_title_color'),
        ('assistant', '0006_auto_20180202_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='catalog_manufacturer', to='catalog.Manufacturer'),
        ),
    ]
