# Generated by Django 2.0.1 on 2018-03-03 19:23

from django.db import migrations, models
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_product_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RozetkaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл/Выкл')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=None, related_name='children', to='assistant.RozetkaCategory')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_rozetka',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=None, to='assistant.RozetkaCategory', verbose_name='Категория розетка'),
        ),
    ]
