# Generated by Django 2.0.1 on 2018-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_auto_20180303_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rozetkacategory',
            options={'verbose_name': 'Категория розетка', 'verbose_name_plural': 'Категории розетки'},
        ),
        migrations.AddField(
            model_name='product',
            name='import_to_rozetka',
            field=models.BooleanField(default=False, verbose_name='Импортировать на розетку'),
        ),
        migrations.AlterField(
            model_name='rozetkacategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Категория розетка'),
        ),
    ]
