# Generated by Django 2.0.3 on 2018-04-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_auto_20180303_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_to_prom',
            field=models.BooleanField(default=False, verbose_name='Импортировать на PROM'),
        ),
    ]
