# Generated by Django 2.0.3 on 2018-04-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_product_import_to_prom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='import_to_prom',
            field=models.BooleanField(default=False, verbose_name='На PROM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='import_to_rozetka',
            field=models.BooleanField(default=False, verbose_name='На розетку'),
        ),
    ]
