# Generated by Django 2.0.2 on 2018-06-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_product_availability_prom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability_prom',
            field=models.CharField(blank=True, default='+', help_text='\nНаличие товара на складе\n"+" — есть в наличии\n"!" — гарантия наличия (для сертифицированных компаний)\n"-" — нет в наличии\n"&" — ожидается\n"@" — услуга\nцифра, например, "9" — кол-во дней на доставку, если товар под заказ\nВажно! При пустом поле статус вашего товара станет «Нет в наличии».\n', max_length=3, verbose_name='Наличие товара для прома'),
        ),
    ]
