# Generated by Django 2.0.2 on 2018-07-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0015_auto_20180628_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
