# Generated by Django 2.0.2 on 2018-08-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0016_auto_20180722_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
