# Generated by Django 2.0.2 on 2018-08-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0017_auto_20180805_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-code',), 'permissions': (('Can update mizol prices', 'can_update_mizol_prices'),), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
