# Generated by Django 2.0.2 on 2018-08-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0018_auto_20180806_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discont',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Скидка'),
        ),
    ]
