# Generated by Django 2.0.2 on 2018-08-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0020_auto_20180807_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-code',), 'permissions': (('Can update mizol prices', 'can_update_mizol_prices'), ('Freelanser', 'freelanser')), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
