# Generated by Django 2.0.2 on 2018-09-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0024_auto_20180915_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-code',), 'permissions': (('can_update_mizol', 'Может обновлять прайсы Мизол'), ('Freelanser', 'freelanser')), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
