# Generated by Django 2.0.2 on 2018-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0026_auto_20180915_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
