# Generated by Django 2.0.2 on 2019-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0027_auto_20181213_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Наценка в процентах для старай цены'),
        ),
    ]
