# Generated by Django 2.0.2 on 2019-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0029_auto_20191008_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_in_package',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во в упаковке'),
        ),
    ]
