# Generated by Django 2.0.2 on 2019-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0030_auto_20191109_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Наценка в процентах для промо'),
        ),
    ]
